add support for asf files and nice -19 the encode

diff --git a/auto-reencode b/auto-reencode
--- a/auto-reencode
+++ b/auto-reencode
@@ -25,14 +25,14 @@ report() {
 pass1() {
   # For syntax, see: https://trac.ffmpeg.org/wiki/Encode/H.264
 
-  ffmpeg -v quiet -stats -y -i "${file}" \
+  nice -19 ffmpeg -v quiet -stats -y -i "${file}" \
     -c:v libx264 -preset slow -b:v "$vkbps"k -pass 1 \
     -passlogfile "$logfile" \
     -c:a aac -b:a "$akbps"k -f mp4 /dev/null
 }
 
 pass2() {
-  ffmpeg -v quiet -stats -i "${file}" -c:v libx264 \
+  nice -19 ffmpeg -v quiet -stats -i "${file}" -c:v libx264 \
     -preset slow -b:v "$vkbps"k -pass 2 \
     -passlogfile "$logfile" \
     -c:a aac -b:a "$akbps"k "${file%.*}.mp4"
@@ -50,7 +50,7 @@ else
 fi
 
 IFS=$'\012'
-echo 'Enter target file extension [flv,wmv]:'
+echo 'Enter target file extension [flv,wmv,asf]:'
 read -r EXT
 
 # check for files to work on and exit if not are found
@@ -59,9 +59,12 @@ if [[ -z $(find . ! -name . -prune -type f -name "*.$EXT" 2>/dev/null) ]]; then
   if [[ -z $(find . ! -name . -prune -type f -name "*.$EXT" 2>/dev/null) ]]; then
     EXT="wmv"
     if [[ -z $(find . ! -name . -prune -type f -name "*.$EXT" 2>/dev/null) ]]; then
-      echo -e "${BLD}Cannot find any target files so no work to do.${NRM}"
-      echo -e "${BLD}Define a target file type in this dirtree and try again.${NRM}"
-      exit 1
+      EXT="asf"
+      if [[ -z $(find . ! -name . -prune -type f -name "*.$EXT" 2>/dev/null) ]]; then
+        echo -e "${BLD}Cannot find any target files so no work to do.${NRM}"
+        echo -e "${BLD}Define a target file type in this dirtree and try again.${NRM}"
+        exit 1
+      fi
     fi
   fi
 fi
